---
# The behavior of RuboCop can be controlled via the .rubocop.yml
# configuration file. It makes it possible to enable/disable
# certain cops (checks) and to alter their behavior if they accept
# any parameters. The file can be placed either in your home
# directory or in some project directory.
#
# RuboCop will start looking for the configuration file in the directory
# where the inspected file is and continue its way up to the root directory.
#
# See https://docs.rubocop.org/rubocop/configuration
inherit_from:
  - .rubocop_todo.yml

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.5

Layout/LineLength:
  Exclude:
    - 'lib/dspace.rb'
    - 'lib/dspace/core/eperson.rb'

Metrics/AbcSize:
  Exclude:
    - 'lib/dspace.rb'
    - 'lib/dspace/config.rb'
    - 'lib/dspace/core/dspace_object_behavior.rb'
    - 'lib/dspace/core/eperson.rb'
    - 'lib/dspace/core/item.rb'
    - 'lib/dspace/core/metadata_field.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'lib/dspace/core/work.rb'

Metrics/MethodLength:
  Exclude:
    - 'lib/dspace/core/item.rb'
    - 'lib/dspace/core/work.rb'
    - 'lib/dspace/core/eperson.rb'
    - 'lib/dspace/core/group.rb'
    - 'lib/dspace/core/dspace_object_behavior.rb'
    - 'lib/dspace.rb'
    - 'lib/dspace/config.rb'
    - 'lib/dspace/core/dspace_object_behavior.rb'
    - 'lib/dspace/core/eperson.rb'
    - 'lib/dspace/core/group.rb'
    - 'lib/dspace/core/item.rb'
    - 'lib/dspace/core/work.rb'

Metrics/ModuleLength:
  Exclude:
    - 'lib/dspace.rb'
